### ISSUE TITLE
Calling OCaml from JS fails with indirect call to null

### ISSUE THREAD

**Issue by copy** [remixlabs/wasicaml#28]
I've prepared a minimal demo at https://github.com/copy/wasicaml-demo/tree/js_to_ocaml. It fails in Firefox with "RuntimeError: indirect call to null" and in Chromium with "RuntimeError: function signature mismatch".

The C call works (i.e., this line gets printed: https://github.com/copy/wasicaml-demo/blob/js_to_ocaml/stubs.c#L12). The assertion below also doesn't fail, so the issue is likely in `caml_callback`.

**Comment by gerdstolpmann** [comment]
I can reproduce this. Looks like it is trying to run the bytecode interpreter, as you can see from the stack trace:
```
$ ./wasi_run _build/test.wasm 
Hello from wasm+OCaml!
fib(20) = 6765
C call works

WASM error: RuntimeError: function signature mismatch
RuntimeError: function signature mismatch
    at interpret_inner (<anonymous>:wasm-function[674]:0x71010)
    at interpret_inner_untyped (<anonymous>:wasm-function[673]:0x6f16b)
    at wasicaml_call (<anonymous>:wasm-function[24]:0xf2d)
    at /Users/gerd/tmp/wasicaml-demo/main.js:23:38
    at wasicaml_wraptry (<anonymous>:wasm-function[22]:0xed5)
    at caml_interprete (<anonymous>:wasm-function[672]:0x6f142)
    at caml_callbackN_exn (<anonymous>:wasm-function[1018]:0x84cbb)
    at caml_callback (<anonymous>:wasm-function[1020]:0x84d4a)
    at js_to_ocaml (<anonymous>:wasm-function[655]:0x6d768)
    at instantiate (/Users/gerd/tmp/wasicaml-demo/main.js:201:30)
```

Here, `wasi_run` is a local copy, and I added the call to `js_to_ocaml` at the end of the `instantiate` function, like
```
async function instantiate(wasm_mod, args) {
    ....
    session.instance = await WebAssembly.instantiate(wasm_mod, importObject);
    wasi.start(session.instance);
    session.instance.exports.js_to_ocaml()    // ADDED LINE
}
```

In deed, `caml_callbackN_exn` (see https://github.com/ocaml/ocaml/blob/trunk/runtime/callback.c#L54) is written for bytecode and would have to be changed for wasicaml.

**Comment by gerdstolpmann** [comment]
@copy Can you check whether #29 closes the issue for you?

**Comment by copy** [comment]
@gerdstolpmann Yes, this fixes the issue for me. Cheers!
